# Generated by Django 5.0.6 on 2024-07-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_blog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('deraction', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Team/images')),
            ],
        ),
    ]
